name: Echo Context Variable

on:
  push:
    branches:
      - main

jobs:
  echo-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Context Variable
        run: "echo \"My context variable is: ${{ github.repository }}\""
