name: Pull Request Destination Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # branches-ignore:
    #   - main
    paths:
      - watched/**

jobs:
  print-destination-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print Destination Branch
        run: "echo \"Destination branch name: ${{ github.head_ref }}\""